# Site Information
title: D P Bennett & Associates
description: This is the D P Bennett & Associates corporate website.
baseurl: ""
url: "https://dpbennett.com.jm"

# Company Information
company_name: D P Bennett & Associates Ltd.
company_abbrev: DPB&A
address_line: Kingston
country: Jamaica
company_email: info@dpbennett.com.jm

disqus:
  username: news-brief

# Social Links
facebook_link: https://www.facebook.com/desmondpbennett/
twitter_link: https://twitter.com/DPB_and_A
github_link: https://github.com/DPBandA

collections:
  jmts-doc:
      output: true    

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate-v2
  - jekyll-disqus

permalink: pretty
excerpt_separator: <!--more-->

defaults:
  - scope:
      path: ""
    values:
      image: "https://dpbennett.com.jm/assets/media/logo.png"
      description: "Welcome to the D P Bennett & Associates Ltd. website! We specialize in delivering cutting-edge engineering and information technology solutions."

jekyll_admin:
  hidden_links:
    - configuration
  homepage: "pages"
  
include:
  - service-worker.js
  - assets/manifest.json
  - assets/icons
